version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dashpivot_db
    environment:
      POSTGRES_USER: akopyan_albert
      POSTGRES_PASSWORD: za1avGU8
      POSTGRES_DB: pivotdash
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: dashpivot_server
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/pivotdash"
      DATABASE_USER: akopyan_albert
      DATABASE_PASSWORD: za1avGU8
    ports:
      - "8085:8085"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
    driver: local