version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pivotdash
    environment:
      POSTGRES_USER: akopyan_albert
      POSTGRES_PASSWORD: za1avGU8
      POSTGRES_DB: pivotdash
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  db_data:
    driver: local