name: Build JVM Application

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build JAR
        run: ./gradlew :jvm:build

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: jvm-jar
          path: jvm/build/libs/*.jar
