name: Deploy Server

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        run: git push heroku ${{ github.ref_name }}:main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}