name: Build and Deploy Project

on:
  push:
    branches:
      - dev
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - dev
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Build Server
        run: ./gradlew :server:build -x test

      - name: Deploy to Heroku
        run: git push heroku HEAD:main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Android APK
        run: ./gradlew :androidApp:assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: androidApp/build/outputs/apk/release/*.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: xcode-select --switch /Applications/Xcode_13.4.app  # Укажите версию Xcode, если требуется

      - name: Build iOS App
        run: |
          cd iosApp
          xcodebuild -scheme iosApp -sdk iphonesimulator -configuration Release

      - name: Upload iOS Build
        uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: iosApp/build/Release-iphonesimulator/*.app

  build-jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Build JVM Application
        run: ./gradlew :jvmApp:build

      - name: Upload JVM Build
        uses: actions/upload-artifact@v2
        with:
          name: jvm-app
          path: jvmApp/build/libs/*.jar